error: method's name is the same as an existing method in a trait
  --> $DIR/same_name_method.rs:22:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^
   |
note: existing `foo` defined here
  --> $DIR/same_name_method.rs:26:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^
   = note: `-D clippy::same-name-method` implied by `-D warnings`

error: method's name is the same as an existing method in a trait
  --> $DIR/same_name_method.rs:36:13
   |
LL |             fn clone() {}
   |             ^^^^^^^^^^^^^
   |
note: existing `clone` defined here
  --> $DIR/same_name_method.rs:32:18
   |
LL |         #[derive(Clone)]
   |                  ^^^^^
   = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)

error: method's name is the same as an existing method in a trait
  --> $DIR/same_name_method.rs:46:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^
   |
note: existing `foo` defined here
  --> $DIR/same_name_method.rs:50:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^

error: method's name is the same as an existing method in a trait
  --> $DIR/same_name_method.rs:60:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^
   |
note: existing `foo` defined here
  --> $DIR/same_name_method.rs:63:9
   |
LL |         impl T1 for S {}
   |         ^^^^^^^^^^^^^^^^

error: method's name is the same as an existing method in a trait
  --> $DIR/same_name_method.rs:72:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^
   |
note: existing `foo` defined here
  --> $DIR/same_name_method.rs:75:9
   |
LL |         impl T1 for S {}
   |         ^^^^^^^^^^^^^^^^

error: aborting due to 5 previous errors

